### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by dineshks1** [comment]
Please review this merge.

**Comment by stephank** [comment]
Sorry, I don't think this is very useful? This library is pure JS and uses very basic functionality. It'd be more useful to test JS engines themselves (like V8) on other architectures.

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,For more info tag @gerrith3.

**Comment by dineshks1** [comment]
Please review this merge.

**Comment by stephank** [comment]
Sorry, I wasn't correctly receiving notifications for this repo, but I'm about to archive it. I hope this won't block you, but I don't think this library is necessary anymore on any modern JavaScript engine.

**Pull request closed without merging**
